"""add hospital.purchases table

Revision ID: 02d65a232d9c
Revises: d767e4f241bf
Create Date: 2026-07-11 13:19:09.186887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02d65a232d9c'
down_revision: Union[str, Sequence[str], None] = 'd767e4f241bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('medicine_id', sa.Uuid(), nullable=False),
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('stock_id', sa.Uuid(), nullable=True),
    sa.Column('batch_number', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.CheckConstraint('quantity >= 0', name=op.f('ck_purchases_quantity_non_negative')),
    sa.CheckConstraint('unit_price >= 0', name=op.f('ck_purchases_unit_price_non_negative')),
    sa.ForeignKeyConstraint(['medicine_id'], ['hospital.medicines.id'], name=op.f('fk_purchases_medicine_id_medicines'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['stock_id'], ['hospital.stocks.id'], name=op.f('fk_purchases_stock_id_stocks'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_id'], ['hospital.suppliers.id'], name=op.f('fk_purchases_supplier_id_suppliers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchases')),
    schema='hospital'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('purchases', schema='hospital')
    # ### end Alembic commands ###
