"""add platform.audit_logs table

Revision ID: e32be86134f9
Revises: 02d65a232d9c
Create Date: 2026-07-12 14:51:54.775116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e32be86134f9'
down_revision: Union[str, Sequence[str], None] = '02d65a232d9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=False),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['platform.users.id'], name=op.f('fk_audit_logs_actor_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs')),
    schema='platform'
    )

    op.create_index(
        "ix_platform_audit_logs_entity",
        "audit_logs",
        ["entity_type", "entity_id"],
        schema="platform",
    )

    op.create_index(
        "ix_platform_audit_logs_created_at",
        "audit_logs",
        ["created_at"],
        schema="platform",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_platform_audit_logs_created_at", table_name="audit_logs", schema="platform")
    op.drop_index("ix_platform_audit_logs_entity", table_name="audit_logs", schema="platform")
    op.drop_table('audit_logs', schema='platform')
    # ### end Alembic commands ###
