"""create users table

Revision ID: fc22947f0479
Revises: f1641faf1913
Create Date: 2026-07-04 14:59:58.547161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc22947f0479'
down_revision: Union[str, Sequence[str], None] = 'f1641faf1913'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    schema='platform'
    )
    op.create_index(op.f('ix_platform_users_email'), 'users', ['email'], unique=True, schema='platform')
    op.create_index(op.f('ix_platform_users_username'), 'users', ['username'], unique=True, schema='platform')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_platform_users_username'), table_name='users', schema='platform')
    op.drop_index(op.f('ix_platform_users_email'), table_name='users', schema='platform')
    op.drop_table('users', schema='platform')
    # ### end Alembic commands ###
